apiVersion: v1
kind: ServiceAccount
metadata:
  name: goserver-sa


---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: goserver-role
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: goserver-rolebinding
subjects:
- kind: ServiceAccount
  name: goserver-sa
  namespace: matheusses-dev
roleRef:
  kind: Role
  name: goserver-role
  apiGroup: rbac.authorization.k8s.io