apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: matheus.s.es@gmail.com
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-tls
    solvers:
    - http01:
        ingress:
          class: nginx
